version: '3.8'

services:
  backend:
    image: 209314125202.dkr.ecr.ap-southeast-1.amazonaws.com/backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: 209314125202.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
    ports:
      - "80:80"

